# Generated by Django 4.0.4 on 2022-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Enter email address.",
                max_length=254,
                unique=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Enter a password.", max_length=100, verbose_name="Password"
            ),
        ),
    ]
