# Generated by Django 4.0.4 on 2022-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total amount of all products automatically generated.",
                max_digits=10,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Enter product name.", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="out_of_stock",
            field=models.BooleanField(
                default=False,
                help_text="Check if product is in stock",
                verbose_name="Out of Stock",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter product price.",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(
                default=1,
                help_text="Enter quantity of product to get.",
                verbose_name="Quantity",
            ),
        ),
    ]
